- HikingClub.xcodeproj/project.pbxproj
- HikingClub/Base.lproj/Main.storyboard
- HikingClub/MainTabBarController.swift
> Base MainTabBar 구현

- HikingClub.xcodeproj/project.pbxproj
- HikingClub/Extension/UIButton+.swift
> UIButton 폰트 익스텐션구현

- HikingClub/HitThemeHeaderCollectionViewCell.swift
- HikingClub/HitThemeHeaderCollectionViewCell.xib
- HikingClub/HitThemeTableHeaderView.swift
- HikingClub/HitThemeTableHeaderView.xib
- HikingClub/Home.storyboard
- HikingClub/HomeViewController.swift
> :blub: 홈 테이블뷰 헤더 연결

- HikingClub/Helper/Components/NDSearchTextField.swift
> :bulb: 검색텍스트필드 텍스트수정기능 추가

- HikingClub/Helper/Components/ComponentTestViewController.swift
- HikingClub/Helper/Components/NDTabButton.swift
- HikingClub/Helper/Components/NaviBar.swift
- 토글 접근범위변경
- 터치 비활성화함수구현
- 네비바 타이틀 바인더구현
toggle함수 접근제어 public으로 변경
> :bulb: 텝버튼 컨트롤 기능 추가

- HikingClub/Helper/Components/ComponentTestViewController.swift
- HikingClub/Helper/Components/NDTabButton.swift
- HikingClub/Helper/Components/NDToastView.swift
> :bulb: 토스트메시지 에러 아이콘추가

- HikingClub/Helper/Components/NDTabButton.swift
죄송함다.. 잦은 pr...
자꾸수정사항이생기네...
텝버튼 로직개선
> :bulb: 텝버튼 로직개선

- HikingClub.xcodeproj/project.pbxproj
- HikingClub/Helper/Extension/UITableViewCell+.swift
> :bulb: Cell 클릭컬러 커스텀화 extension추가

- HikingClub/Helper/Components/NaviBar.swift
> :bulb: 오른쪽버튼 틴트컬러 추가기능 구현

- HikingClub.xcodeproj/project.pbxproj
- HikingClub/Feature/SelectTown/SelectTownViewController.swift
- HikingClub/Feature/SelectTown/SelectTownViewModel.swift
- HikingClub/Feature/SelectTown/View/SelectTownTableViewCell.swift
- HikingClub/SupportingFiles/Info.plist
#64 
* 동네설정 화면 UI작업 완료
* 동네설정 화면 API 연결 완료
* 현재 위치로 동네 검색 API 연결 예정
> 동네선택 화면 UI 완료

- HikingClub/Feature/Home/Home.storyboard
- HikingClub/Feature/Home/HomeViewController.swift
- HikingClub/Feature/Home/HomeViewModel.swift
- HikingClub/Feature/Home/View/HitTheme/HeaderCollectionViewCell/HitThemeHeaderCollectionViewCell.swift
- HikingClub/Feature/Home/View/HitTheme/HeaderCollectionViewCell/HitThemeHeaderCollectionViewCell.xib
- HikingClub/Feature/Home/View/HitTheme/TableHeaderView/HitThemeTableHeaderView.swift
- HikingClub/Feature/Home/View/HitTheme/TableHeaderView/HitThemeTableHeaderView.xib
- HikingClub/Feature/Search/SearchCategoryResultViewController.swift
- HikingClub/Feature/Search/SearchResultViewController.swift
- HikingClub/Helper/Extension/UIView+.swift
#18 
- 가로 그라데이션 UIView+ 구현
- 변경된 디자인 헤더 적용
- 레이아웃 오류제거
- 위치탭바 추가버튼 구현
- 탭바 최초 선택되는 시점변경
이때문에 `Home` 뿐만아니라 `Search` 쪽도 건드림... 🙏
> 홈화면 헤더 변경작업

- HikingClub/Feature/Search/SearchCategoryResultViewController.swift
- HikingClub/Feature/WebView/BaseWebView.swift
- HikingClub/Feature/WebView/WebViewController.swift
- HikingClub/Feature/WebView/WebViewModel.swift
* 웹뷰 뷰모델 적용
* 웹뷰 - 웹 페이지 메세지 프로토콜 정의
https://www.notion.so/706ba90c4b664d44873c4c4a32505d88
> 웹뷰 - 웹 메세지 프로토콜

- HikingClub.xcodeproj/project.pbxproj
- HikingClub/Feature/Home/HomeViewController.swift
- HikingClub/Feature/Login/SignUp/EmailAuthorize/EmailAuthorizeViewModel.swift
- HikingClub/Feature/Login/SignUp/EmailAuthorize/EmailAuthroizeViewController.swift
- HikingClub/Feature/Login/SignUp/InitialSetting/InitialCategorySettingViewController.swift
- HikingClub/Feature/Login/SignUp/InitialSetting/InitialCategorySettingViewModel.swift
- HikingClub/Feature/Login/SignUp/InitialSetting/InitialSettingViewController.swift
- HikingClub/Feature/Login/SignUp/InitialSetting/InitialSettingViewModel.swift
- HikingClub/Feature/Login/SignUp/SignUpInputViewController.swift
- HikingClub/Network/SignUpService/SignUpAPI.swift
- HikingClub/Network/SignUpService/SignUpService.swift
#39 
* 회원가입 후 카테고리 첫 설정 제외 회원가입 로직 마무리
> 회원가입 로직 1차 마무리

- HikingClub/Helper/Components/ComponentTestViewController.swift
- HikingClub/Helper/Components/NDButton/NDCTAButton.swift
https://github.com/mash-up-kr/HikingClub_iOS/pull/77#discussion_r752494020
cta버튼 enabled binder구현
> :bulb: cta버튼 Enabled rx binder 구현

- HikingClub/Feature/Main/MainTabBarController.swift
- HikingClub/Feature/WebView/WebViewController.swift
* 로그인상태(토큰)에 따른 글쓰기 / 마이페이지 진입 분기처리
> 로그인 상태에 따른 글쓰기 / 마이페이지 진입 분기처리

- HikingClub/Feature/Home/HomeViewModel.swift
- HikingClub/Feature/Home/View/Road/TableViewCell/RoadTableViewCell.swift
> 홈화면 서버연결 및 개선

- HikingClub.xcodeproj/project.pbxproj
- HikingClub/Helper/Components/NDIndicator.swift
- HikingClub/Network/Base/NetworkProvider.swift
NetworkProvider에 indicator activity plugin 구현
> :bulb: 네트워크 통신시 indicator 표시

- HikingClub/Feature/Main/MainTabBarController.swift
https://www.notion.so/iOS-79338acb4ea547be96a2848fdf9f40bf
* 길등록 웹뷰 노출 시 `.fullScreen` 적용
> [QA] 길등록 웹뷰 모달로 뜨는 현상 해결

- HikingClub/Feature/Main/MainTabBarController.swift
* 메인 탭바의 검색 탭 삽입 코드 주석 처리
* 검색 탭바 숨김처리
> 검색 탭바 숨김처리

- HikingClub.xcodeproj/project.pbxproj
- HikingClub/Feature/Login/SignIn/SignInViewModel.swift
- HikingClub/Feature/Main/MainTabBarController.swift
- HikingClub/Feature/MyPage/MyPageViewController.swift
- HikingClub/Feature/MyPage/MyPageViewModel.swift
- HikingClub/Helper/Manager/UserInformationManager.swift
- HikingClub/Network/Base/API.swift
- HikingClub/Network/PlaceService/PlaceAPI.swift
- HikingClub/Network/PlaceService/PlaceService.swift
- HikingClub/Network/PlaceService/Request/PlaceRequestModel.swift
- HikingClub/Network/Users/UserService/Response/Profile.swift
- HikingClub/Network/Users/UserService/UserAPI.swift
- HikingClub/Network/Users/UserService/UserService.swift
#36 
* 마이페이지 내가 작성한 길 리스트 API 연결 
* 탭바에서 마이페이지 선택 시 마지막 선택 인덱스 저장 안하던 이슈 해결
* `UserInformationUserDefault`사용 하던 코드 Manager로 이동.
* 유저정보 통합관리 매니저의 `isSignIn` 값 수정
* 유저의 로그인 상태 (`isSignIn`), 로그인 시점 (`isSignedIn`), 로그아웃 시점(`isSignedOut`) 체크 가능
> 마이페이지 리스트 구현

- HikingClub/Feature/Login/LoginNavigationViewController.swift
* 뻘짓하다 브랜치 날려먹음 ^^ 
* https://github.com/mash-up-kr/HikingClub_iOS/pull/89랑 같은내용
> [QA] 로그인 네비게이션 로띠 멈춤현상

- HikingClub.xcodeproj/project.pbxproj
- HikingClub/Feature/SelectTown/SelectTownViewController.swift
- HikingClub/Feature/SelectTown/SelectTownViewModel.swift
- HikingClub/Helper/Manager/NDLocationManager.swift
- HikingClub/Network/PlaceService/PlaceService.swift
- HikingClub/Network/PlaceService/Request/PlaceRequestModel.swift
#64 
* 위치정보를 공통으로 사용하도록 `NDLocationManager`추가
* 위치정보 요청 모델에 lat, long 추가
> 동네 선택 화면 현재 위치 검색 API 연결

- HikingClub/Feature/Home/HomeViewController.swift
* 길 상세 페이지 진입 시 탭바 숨기기
📷 |before|after
--|--|--
--|![Simulator Screen Shot - iPhone 11 Pro - 2021-11-28 at 16 23 50](https://user-images.githubusercontent.com/39300449/143733676-5a16673e-2348-4277-a657-792532e02256.png)|![Simulator Screen Shot - iPhone 11 Pro - 2021-11-28 at 16 19 48](https://user-images.githubusercontent.com/39300449/143733653-4df55ef0-495f-427f-9aa5-2d1c217acf23.png)
> [QA] 길 상세 웹뷰 페이지 진입 시 탭바 숨기기

- HikingClub.xcodeproj/project.pbxproj
- HikingClub/Feature/Home/HomeViewModel.swift
- HikingClub/Helper/Extension/UserDefault+.swift
- HikingClub/Helper/Manager/FirstUserManager.swift
- HikingClub/SupportingFiles/AppDelegate.swift
- HikingClub/SupportingFiles/SceneDelegate.swift
> :bulb: 앱 최초시작 확인하기

- HikingClub/Feature/Home/HomeViewModel.swift
- HikingClub/Feature/Settings/SettingViewController.swift
- HikingClub/Feature/Settings/VersionInfoMenu/VersionInfoViewController.swift
- HikingClub/Feature/Settings/VersionInfoMenu/VersionInfoViewModel.swift
- HikingClub/Feature/Settings/View/MenuButtonView.swift
> :bulb: 현재 앱 버전 표시

- HikingClub.xcodeproj/project.pbxproj
- HikingClub/Feature/Home/HomeViewModel.swift
- HikingClub/Feature/Login/LoginNavigationViewController.swift
- HikingClub/Feature/WebView/BaseWebView.swift
- HikingClub/Feature/WebView/WebViewController.swift
- HikingClub/Feature/WebView/WebViewModel.swift
- HikingClub/Helper/Components/NDToastView.swift
- HikingClub/SupportingFiles/Info.plist
* 토큰만료일 5년 -> 1개월 수정
* 길 등록 페이지 진입 시 현재위치가 있는 유저는 현재위치 전달
* 웹페이지의 토큰만료 메세지 처리
* 웹페이지의 공유하기 메세지 대응
* 카메라 촬영 시 권한 요청 문구 추가
* 회원가입 버튼 문구 변경
* NDToastView `numberOfLines` 수정
> [QA] 2차 dev QA

- HikingClub/Feature/Home/View/Road/RoadHashTagView.swift
- HikingClub/Feature/Home/View/Road/TableViewCell/RoadTableViewCell.swift
길태그 앞에 `#`추가
변수명오타 수정
distribute속성이 fill때문에 늘어난 태그가 있는 이슈가 있어서 수정
(fill -> eqaul spacing)
> :bulb: 태그앞에 #표시추가

- HikingClub/Feature/Login/SignUp/SignUpViewController.swift
#112 
* https://github.com/mash-up-kr/HikingClub_iOS/pull/114#discussion_r767244765 피드백 내용 반영
> [Bug] 약관 동의 후, 약관페이지를 통한 약관동의 시 상태 업데이트 안되던 현상 대응

- HikingClub/Feature/Onboarding/MainOnboardingViewController.swift
#113 
* .gray400 -> .green700 변경
> [QA] 온보딩 입장하기 버튼 컬러 변경

- HikingClub/Feature/Home/HomeViewController.swift
- HikingClub/Feature/Home/HomeViewModel.swift
- HikingClub/Feature/Search/View/EmptyView.swift
#116 
* 위치 권한 별 EmptyView 문구 변경
-|위치권한 OFF|위치권한 ON
--|--|--
-|![IMG_3478](https://user-images.githubusercontent.com/39300449/146397586-dd243f6b-616f-4869-bd13-58bd711d679f.PNG)|![IMG_3477](https://user-images.githubusercontent.com/39300449/146397578-a79c00e7-ad06-456f-9997-4b4234bbdbe7.PNG)
> [QA] 위치 권한 및 홈 리스트 콘텐츠 별 가이드 문구 변경
